# Generated by Django 4.0.3 on 2022-03-31 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('isinnumber', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('paidup', models.FloatField()),
                ('marketlot', models.IntegerField()),
                ('facevalue', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NSEStockPriceApp.company')),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NSEStockPriceApp.series')),
            ],
        ),
        migrations.CreateModel(
            name='Bhavcopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('last', models.FloatField()),
                ('previousclose', models.FloatField()),
                ('totaltrdq', models.FloatField()),
                ('totaltrdv', models.FloatField()),
                ('time', models.CharField(max_length=100)),
                ('trades', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NSEStockPriceApp.company')),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NSEStockPriceApp.series')),
            ],
        ),
    ]
