# Generated by Django 4.0.3 on 2022-03-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NSEStockPriceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securities',
            old_name='data',
            new_name='date',
        ),
    ]
